# Generated by Django 5.1.4 on 2024-12-09 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=350, verbose_name='Полное имя'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=350, verbose_name='Оригинальное имя файла')),
                ('unique_name', models.CharField(max_length=350, unique=True, verbose_name='Уникальное имя файла')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер файла (в байтах)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
