# Generated by Django 5.1.4 on 2024-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_customuser_full_name_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Полное имя'),
        ),
    ]
