# Generated by Django 5.1.4 on 2024-12-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_filetoken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='filetoken',
            options={'verbose_name': 'Токен файла', 'verbose_name_plural': 'Токены файлов'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
        migrations.AlterModelTable(
            name='filetoken',
            table='FileToken',
        ),
    ]
